namespace FileManager.Api.Infrastructure;

public static class TabLease
{
    /// <summary>Header carrying the per-tab identifier generated by the SPA.</summary>
    public const string HeaderName = "X-Tab-Id";

    /// <summary>Set by the authentication handler when the session belongs to another tab.</summary>
    public const string ConflictItemKey = "fm:tab-conflict";

    public const string ConflictCode = "tab-conflict";
}

/// <summary>
/// Rejects requests coming from a second tab of the same browser: a session is owned by the tab that
/// claimed it first, and the other tab gets a clear conflict instead of silently sharing access.
/// </summary>
public sealed class TabLeaseMiddleware
{
    private readonly RequestDelegate _next;

    public TabLeaseMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        if (context.GetEndpoint() is not null && context.Items.ContainsKey(TabLease.ConflictItemKey))
        {
            context.Response.StatusCode = StatusCodes.Status409Conflict;
            await context.Response.WriteAsJsonAsync(
                new
                {
                    title = "Конфликт вкладок",
                    status = StatusCodes.Status409Conflict,
                    detail = "Приложение уже открыто в другой вкладке этого браузера. Закройте лишнюю вкладку.",
                    code = TabLease.ConflictCode,
                },
                context.RequestAborted).ConfigureAwait(false);
            return;
        }

        await _next(context).ConfigureAwait(false);
    }
}
